name: Android Pipeline

on: [push]

jobs:
  # tests:
  #   runs-on: ubuntu-latest
  #   environment: stage
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v3

  #     - name: Set up Ruby
  #       uses: actions/setup-ruby@v1
  #       with:
  #         ruby-version: '3'

  #     - name: Install Dependencies
  #       run: gem install bundler && bundle install

  #     - name: Tests
  #       run: fastlane Test

  build_demo:
    # needs: tests
    runs-on: ubuntu-latest
    environment: stage
    env:
      TEST_KEY: ${{ secrets.TEST_KEY }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'

      - name: Install Dependencies
        run: gem install bundler && bundle install

      - name: Build-demo
        run: fastlane BuildDemo

      # - name: Save .apk in artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: example-release.apk
      #     path: example/build/outputs/apk/release/example-release.apk

  # deploy_demo:
  #   needs: build_demo
  #   runs-on: ubuntu-latest
  #   environment: stage
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v3

  #     - name: Set up Ruby
  #       uses: actions/setup-ruby@v1
  #       with:
  #         ruby-version: '3'

  #     - name: Install Dependencies
  #       run: gem install bundler && bundle install

  #     - name: Deploy-demo
  #       run: fastlane DeployDemo
