name: Android Pipeline

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'

      - name: Install Dependencies
        run: gem install bundler && bundle install

  build_demo:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'

      - name: Install Dependencies
        run: gem install bundler && bundle install

      - name: Build-demo
        run: fastlane BuildDemo

  deploy_demo:
    needs: build_demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'

      - name: Install Dependencies
        run: gem install bundler && bundle install

      - name: Deploy-demo
        run: fastlane DeployDemo
